name: Check PR semantics

on:
  pull_request_target:

permissions: {}

jobs:
  cpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Check PR semantics
        uses: ./
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          edit: true
          verbose: true
